---
- name: Rclone | Install fuse (RHEL/CentOS/Fedora)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - fuse
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

- name: Rclone | Install fuse (Debian/Ubuntu)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - fuse3
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Rclone | Install Rclone via shell
  ansible.builtin.shell:
    cmd: curl https://rclone.org/install.sh | sudo bash
    creates: /usr/bin/rclone

- name: Rclone | Copy rclone config file from local machine
  ansible.builtin.copy:
    src: files/rclone.conf
    dest: /etc/rclone.conf
    owner: root
    group: root
    mode: 0644

- name: Rclone | Create rclone config directory
  ansible.builtin.file:
    path: /root/.config/rclone/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Rclone | Remove rclone config file to avoid symlink error
  ansible.builtin.file:
    path: /root/.config/rclone/rclone.conf
    state: absent

- name: Rclone | Link rclone config to /root/.config/rclone/rclone.config
  ansible.builtin.file:
    src: /etc/rclone.conf
    dest: /root/.config/rclone/rclone.conf
    state: link

- name: Rclone | Create rclone mount directory
  ansible.builtin.file:
    path: /mnt/cryptdrive
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Rclone | create log file
  ansible.builtin.file:
    path: /var/log/cryptdrive.log
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Rclone | copy systemd unit file
  ansible.builtin.copy:
    src: rclone.service
    dest: /etc/systemd/system/rclone.service
    owner: root
    group: root
    mode: 0644

- name: Rclone | Enable rclone service
  ansible.builtin.systemd:
    name: rclone
    enabled: yes

- name: Rclone | Restart rclone service
  ansible.builtin.systemd:
    name: rclone
    state: restarted

- name: Rclone | Test if service is running
  shell: systemctl is-active --quiet rclone
  register: rcloneServiceRunning
  ignore_errors: true

- name: Rclone | Test if /mnt/cryptdrive is not empty
  find:
    paths: /mnt/cryptdrive
    file_type: any
  register: cryptdriveEmpty

- fail:
    msg: "rclone service is not running"
  when: rcloneServiceRunning.rc != 0

- fail: 
    msg: "/mnt/cryptdrive is empty"
  when: cryptdriveEmpty.matched == 0

- name: Rclone | Test if backup rclone remote exists
  shell: "rclone --config /etc/rclone.conf ls backup:"
  register: backupRemoteExists

- fail:
    msg: "backup rclone remote does not exist"
  when: backupRemoteExists.rc != 0
