---
- name: Init
  gather_facts: false
  hosts: all
  roles:
    - { role: common, tags: ["common"] }
    - { role: checkUser, tags: ["common", "check", "debug"] }
    - { role: updateOS, tags: ["update"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: configureRclone, tags: ["rclone"] }
    - { role: configureBackup, tags: ["restic", "rclone"] }
  ignore_errors: yes
  become: yes
  