---
- name: Install Podman
  package:
    name: podman
    state: present
    update_cache: yes
  tags: [podman]

- name: Install Podman Compose
  package:
    name: podman-compose
    state: present
  tags: [podman]

- name: Create Podman Group
  group:
    name: podman
    state: present
  tags: [podman]

- name: Add User to Podman Group
  user:
    name: "{{ item }}"
    groups: podman
    append: yes
  tags: [podman]
  with_items:
    - ansible
    - "{{ main_user }}"
  
- name: Enable Podman Service
  systemd:
    name: podman.socket
    enabled: yes
    state: started
  tags: [podman]

- name: Enable Podman Network
  systemd:
    name: podman-network
    enabled: yes
    state: started
  tags: [podman]

- name: Enable Podman Remote Service
  systemd:
    name: podman-remote.socket
    enabled: yes
    state: started
  tags: [podman]
