---
- name: Disable root login over SSH
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - restart sshd

- name: Disable password login
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PasswordAuthentication" 
    line: "PasswordAuthentication no" 
    state: present
  notify:
    - restart sshd

- name: allow passwordless sudo for ansible user
  lineinfile: 
    dest: /etc/sudoers 
    regexp: "^ansible" 
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    state: present
  notify:
    - restart sshd
