---

- name: if git is not installed install it
  ansible.builtin.package:
    name: git
    state: present

- name: check if package pandoc is installed, and install it if not
  ansible.builtin.package:
    name: pandoc
    state: present

- name: install latex on fedora
  ansible.builtin.package:
    name: texlive
    state: present
  when: ansible_distribution == 'Fedora'

- name: install latex on ubuntu
  ansible.builtin.package:
    name: texlive-full
    state: present
  when: ansible_distribution == 'Ubuntu'
  
- name: create group pandoc
  ansible.builtin.group:
    name: pandoc
    state: present

- name: add users to group pandoc
  ansible.builtin.user:
    name: "{{ item }}"
    groups: pandoc
    append: yes
  loop:
    - root
    - ansible
    - "{{ main_user }}"

- name: create a temporary directory for pandoc
  ansible.builtin.file:
    path: /tmp/pandoc
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: find pandoc templates directory
  ansible.builtin.find:
    paths: /usr/share/pandoc
    recurse: no
    file_type: directory
  register: pandoc_templates

- name: clone eisvogel template for pandoc
  ansible.builtin.git:
    repo: https://github.com/Wandmalfarbe/pandoc-latex-template.git
    dest: /tmp/pandoc/pandoc-latex-template
    clone: yes

- name: find pandoc templates directory
  shell: find /usr/share/pandoc-*/data/templates | head -n 1
  register: pandoc_templates

- name: copy eisvogel template to pandoc templates directory
  ansible.builtin.copy:
    src: /tmp/pandoc/pandoc-latex-template/eisvogel.tex
    dest: "{{ pandoc_templates.stdout }}/eisvogel.latex"
    remote_src: yes
    owner: root
    group: root
    mode: '0644'

- name: clone resume template for pandoc
  ansible.builtin.git:
    repo: https://github.com/john-bokma/resume-pandoc.git
    dest: /tmp/pandoc/resume-pandoc
    clone: yes

- name: copy resume template to pandoc templates directory
  ansible.builtin.copy:
    src: /tmp/pandoc/resume-pandoc/templates/jb2-modern.latex
    dest: "{{ pandoc_templates.stdout }}/resume.latex"
    remote_src: yes
    owner: root
    group: root
    mode: '0644'

# Tests

- name: test pandoc installed
  ansible.builtin.shell: pandoc --version
  register: pandoc_version

- name: copy test markdown file
  ansible.builtin.copy:
    src: test.md
    dest: /tmp/test.md
    owner: root
    group: root
    mode: '0644'

# - name: convert test markdown file to pdf (eisvogel template)
#   tags: test
#   ansible.builtin.shell: pandoc /tmp/test.md -o /tmp/test-eisvogel.pdf --template eisvogel --pdf-engine=xelatex
#   register: pandoc_pdf

# - name: convert test markdown file to pdf (resume template)
#   tags: test
#   ansible.builtin.shell: pandoc /tmp/test.md -o /tmp/test-resume.pdf --template resume --pdf-engine=xelatex
#   register: pandoc_pdf

- name: copy test files to ansible controller
  tags: test
  ansible.builtin.fetch:
    src: /tmp/test.md
    dest: /tmp/test.md
    flat: yes
    fail_on_missing: yes
  loop:
    - test-eisvogel.pdf
    - test-resume.pdf

- name: remove test files
  tags: test
  ansible.builtin.file:
    path: /tmp/"{{ item }}"
    state: absent
  loop:
    - test.md
    - test-eisvogel.pdf
    - test-resume.pdf
