---
- name: Check if Variables are set
  assert:
    that: 
      - main_user is defined
      - main_user is not none
      - ansible_distribution is defined and ansible_distribution in ['Debian', 'Ubuntu', 'CentOS', 'RedHat', 'Fedora']
      - hostname is defined
      - hostname is not none
      