---
- name: User | Create user accounts
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: wheel
    update_password: on_create
  ignore_errors: true
  loop:
    - ansible
    - "{{ main_user }}"

- name: User | Set authorized key for user
  ansible.posix.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'public_keys/{{ item }}.pub') }}"
  ignore_errors: true
  loop:
    - ansible
    - "{{ main_user }}"

- name: install vim, git
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - git
