---
- include_tasks: checkVariablesSet.yml
  tags: install
  
- name: User | Create user accounts (rhel based)
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: wheel
    update_password: on_create
  ignore_errors: true
  loop:
    - ansible
    - "{{ main_user }}"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Fedora"

- name: User | Create user accounts (debian based)
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: sudo
    update_password: on_create
  ignore_errors: true
  loop:
    - ansible
    - "{{ main_user }}"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: User | Set authorized key for user
  ansible.posix.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'public_keys/{{ item }}.pub') }}"
  ignore_errors: true
  loop:
    - ansible
    - "{{ main_user }}"

- name: install vim, git
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - git
