---
- name: User | Create user accounts
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: wheel
    update_password: on_create
  ignore_errors: true
  loop:
    - ansible
    - "{{ main_user }}"

- name: User | Set authorized key for user
  ansible.posix.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'public_keys/{{ item }}.pub') }}"
  ignore_errors: true
  loop:
    - ansible
    - "{{ main_user }}"

- name: User | Prompt for main_user password
  ansible.builtin.pause:
    prompt: "Enter password for {{ main_user }}: "
    echo: no
    private: yes
  register: main_user_password

- name: User | Set Password for main_user
  ansible.builtin.user:
    name: "{{ main_user }}"
    password: "{{ main_user_password | password_hash('sha512') }}"
  when: main_user_password is defined

- name: install vim, git
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - git
