---
- name: Postfix | Check if postfix is installed
  ansible.builtin.stat:
    path: /usr/sbin/postfix
  register: postfix_cli

# set variable cert_path
- name: Postfix | Set variable cert_path
  set_fact:
    cert_path: /etc/postfix/cert

- name: Postfix | Set variable country
  set_fact:
    country: "DE"

- name: Postfix | Set variable state
  set_fact:
    state: "Berlin"

- name: Postfix | Set variable locality
  set_fact:
    locality: "Berlin"

- name: Postfix | Set variable organization
  set_fact:
    organization: "Matthias Wünsch"
  
- name: Postfix | Set variable mail_fqdn
  set_fact:
    mail_fqdn: "cronmail.mjwcodr.de"

- name: Postfix | Install postfix
  ansible.builtin.package:
    name: postfix
    state: present
  when: postfix_cli.stat.exists == False

- name: Postfix | Copy main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  
- name: Postfix | Copy master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644

- name: Postfix | Make sure python-firewall is installed for firewalld (RHEL)
  ansible.builtin.package:
    name: python-firewall
    state: present
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

- name: Postfix | Check if firewalld exists
  ansible.builtin.stat:
    path: /usr/bin/firewalld
  register: firewalld

- name: Postfix | Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present
  when: firewalld.stat.exists == False

- name: Postfix | Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Postfix | Open port 587
  ansible.builtin.firewalld:
    port: 587/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Postfix | Create cert for postfix
  ansible.builtin.shell: |
    mkdir -p {{ cert_path }}
    openssl req -new -x509 -days 3650 -nodes -out {{ cert_path }}/cert.pem -keyout {{ cert_path }}/key.pem -subj "/C={{ country }}/ST={{ state }}/L={{ locality }}/O={{ organization }}/CN={{ mail_fqdn }}"

- name: Postfix | Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Postfix | Copy Write message with public ip to console
  debug:
    msg: "Postfix | Public IP: {{ ansible_ssh_host }}"