---
- name: Backup | check if restic is installed and install it if not
  ansible.builtin.package:
    name: restic
    state: present

- name: Backup | update restic
  ansible.builtin.shell: restic self-update
  
- name: Backup | check if /etc/restic exists and create it if not
  ansible.builtin.file:
    path: /etc/restic
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Backup | copy backup list to server
  ansible.builtin.copy:
    src: backup_list
    dest: /etc/restic/backup_list
    owner: root
    group: root
    mode: 0644

- name: Backup | copy exclude list to server
  ansible.builtin.copy:
    src: exclude_list
    dest: /etc/restic/exclude_list
    owner: root
    group: root
    mode: 0644

- name: Backup | copy restic environment file to server
  template:
    src: restic.env.j2
    dest: /etc/restic/restic.env
    owner: root
    group: root
    mode: 0644
    
- name: Backup | copy backup, forget, init and restore scripts to server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/restic/{{ item }}
    owner: root
    group: root
    mode: 0755
  loop:
    - backup.sh
    - forget.sh
    - init.sh
    - restore.sh
    - stats.sh
    - unlock.sh

- name: Backup | get random minute for cron
  ansible.builtin.shell: /usr/bin/shuf -i 0-59 -n 1
  register: random_minute

- name: Backup | restic backup script to cron - run every hour at random minute
  cron: 
    name: "Create Backup"
    minute: "{{ random_minute.stdout }}"
    hour: "*"
    job: "/etc/restic/backup.sh"
    state: present
    user: root
    
- name: Backup | restic forget script to cron - run every 12 hours at random minute
  cron:
    name: "Forget Backup"
    minute: "{{ random_minute.stdout }}"
    hour: "*/12"
    job: "/etc/restic/forget.sh"
    user: root
    state: present

- name: Backup | touch log file
  ansible.builtin.file:
    path: /var/log/restic.log
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Backup | run init script
  ansible.builtin.shell: /etc/restic/init.sh
