---
- name: check if restic is installed and install it if not
  ansible.builtin.package:
    name: restic
    state: present
  
- name: check if /etc/restic exists and create it if not
  ansible.builtin.file:
    path: /etc/restic
    state: directory
    owner: root
    group: root
    mode: 0755

- name: check if /etc/cron.d exists and create it if not
  ansible.builtin.file:
    path: /etc/cron.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy backup list to server
  ansible.builtin.copy:
    src: backup_list
    dest: /etc/restic/backup_list
    owner: root
    group: root
    mode: 0644

- name: copy exclude list to server
  ansible.builtin.copy:
    src: exclude_list
    dest: /etc/restic/exclude_list
    owner: root
    group: root
    mode: 0644

- name: copy restic environment file to server
  ansible.builtin.copy:
    src: files/restic.env
    dest: /etc/restic/restic.env
    owner: root
    group: root
    mode: 0644

- name: copy backup, forget, init and restore scripts to server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/restic/{{ item }}
    owner: root
    group: root
    mode: 0755
  loop:
    - backup.sh
    - forget.sh
    - init.sh
    - restore.sh
    - stats.sh

- name: copy restic cronjobs to server
  ansible.builtin.copy:
    src: restic_cronjobs
    dest: /etc/cron.d/restic
    owner: root
    group: root
    mode: 0644

- name: run init script
  ansible.builtin.shell: /etc/restic/init.sh